from .models.jogadores.Jogador import Jogador
from .models.jogadores.Aleatorio import Aleatorio
from .models.jogadores.Exigente import Exigente
from .models.jogadores.Impulsivo import Impulsivo
from .models.jogadores.Cauteloso import Cauteloso
from .models.jogadores.Aleatorio import Aleatorio
from .models.Propriedade import Propriedade
from .models.Tabuleiro import Tabuleiro
from .models.Relatorio import Relatorio
from .models.Dados import Dados